name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou-test"
database_id = "62513ead-7269-4b88-adb1-1457a7137a63"

[version_metadata]
binding = "CF_VERSION_METADATA"
